# Generated by Django 6.0.4 on 2026-05-07 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0003_alter_institution_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='website',
        ),
    ]
